version: '3.4'
networks:
  example:
    driver: bridge
services:
  backend:
    container_name: api
    image: ${DOCKER_REGISTRY-}example
    build:
      context: .
      dockerfile: Example/Dockerfile
    networks:
        - example
    depends_on:
        - postgres_db
  client:
    container_name: client-react
    image: client
    build:
     context: ./example-client
     dockerfile: Dockerfile
    networks:
        - example
  proxy:
    container_name: proxy-nginx
    image: nginx:mainline
    networks:
        - example
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
       POSTGRES_DB: ${POSTGRES_DB}
    ports:
        - "5432"
    networks:
        - example